# Generated by Django 4.2.3 on 2023-07-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=230)),
                ('unidades', models.CharField(max_length=230)),
                ('localizador', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_de_producto', models.CharField(max_length=230)),
                ('unidades', models.IntegerField(null=True)),
                ('vendedor', models.CharField(max_length=230)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Operador',
            new_name='Personal',
        ),
        migrations.DeleteModel(
            name='Gerente',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
    ]
